name: invictus_trader_pro
description: "Professional Trading App - Cryptocurrency trading platform with real-time analysis and automation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  
  # HTTP & WebSocket
  http: ^1.2.0
  web_socket_channel: ^2.4.4
  
  # HTML Parsing for News Scraping
  html: ^0.15.4
  
  # Charts & Visualization
  candlesticks: ^2.1.0
  fl_chart: ^0.68.0
  
  # Local Storage & Security
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Cryptography
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # AI & Machine Learning
  tflite_flutter: ^0.10.4
  
  # Monetization (Solo suscripciones)
  in_app_purchase: ^3.1.13
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.19.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  
  # Plugin System
  dart_eval: ^0.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/plugins/
    - assets/ml_models/

# Configuración para generar iconos automáticamente
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/icons/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#1A1A1A"
    theme_color: "#FFD700"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
