name: Build APK and EXE

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number override'
        required: false
        default: ''

env:
  FLUTTER_VERSION: '3.27.1'

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate code (if needed)
      run: |
        if [ -f "pubspec.yaml" ] && grep -q "build_runner" pubspec.yaml; then
          flutter packages pub run build_runner build --delete-conflicting-outputs
        fi
      
    - name: Analyze code
      run: flutter analyze --fatal-infos
      
    - name: Run tests
      run: flutter test --coverage
      
    - name: Build APK (Debug)
      run: flutter build apk --debug --build-number=${{ github.run_number }}
      
    - name: Build APK (Release)
      run: flutter build apk --release --build-number=${{ github.run_number }}
      
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          build/app/outputs/flutter-apk/app-debug.apk
          build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Generate code (if needed)
      run: |
        if (Get-Content pubspec.yaml | Select-String "build_runner") {
          flutter packages pub run build_runner build --delete-conflicting-outputs
        }
      shell: powershell
      
    - name: Analyze code
      run: flutter analyze --fatal-infos
      
    - name: Build Windows EXE
      run: flutter build windows --release --build-number=${{ github.run_number }}
      
    - name: Create Windows installer (optional)
      shell: powershell
      run: |
        # Create a simple zip package for now
        $buildPath = "build\windows\x64\runner\Release"
        $outputPath = "invictus-trader-pro-windows.zip"
        if (Test-Path $buildPath) {
          Compress-Archive -Path "$buildPath\*" -DestinationPath $outputPath -Force
          Write-Host "Windows build packaged to $outputPath"
        }
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: |
          build/windows/x64/runner/Release/
          invictus-trader-pro-windows.zip
        retention-days: 30

  build-web:
    name: Build Web (Bonus)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        
    - name: Enable Web
      run: flutter config --enable-web
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release --build-number=${{ github.run_number }}
      
    - name: Upload Web artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/
        retention-days: 30

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-apk, build-windows, build-web]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          ## Invictus Trader Pro - Automated Release
          
          **Changes in this release:**
          - Built from commit: ${{ github.sha }}
          - Build number: ${{ github.run_number }}
          
          **Downloads:**
          - **Android APK**: Download the `app-release.apk` file for Android devices
          - **Windows EXE**: Download the `invictus-trader-pro-windows.zip` file for Windows desktop
          - **Web Version**: Access via GitHub Pages (if deployed)
          
          **Installation Instructions:**
          - **Android**: Enable "Unknown Sources" in settings and install the APK
          - **Windows**: Extract the ZIP file and run `invictustraderapk.exe`
          
          Built with Flutter ${{ env.FLUTTER_VERSION }}
        files: |
          artifacts/android-apk/app-release.apk
          artifacts/android-apk/app-debug.apk
          artifacts/windows-exe/invictus-trader-pro-windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
